# config/packages/nelmio_api_doc.yaml
nelmio_api_doc:
    documentation:
        info:
            title: My Bookmark API
            description: Let's get image and video
            version: 1.0.0
    areas:
        path_patterns: # an array of regexps
            - ^/api(?!/doc$)
        